ingress:
  enabled: true
  hosts:
  - ${domain}
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    cert-manager.io/cluster-issuer: "pfile"
  tls: 
    - secretName: "${domain}-tls"
      hosts:
        - ${domain}
grafana.ini:
  smtp:
    enabled: true
    host: ${mail["implicit-host"]}:587
    ehlo_identity: ${grafana-mail.domain}
    from_address: ${grafana-mail.user}@${grafana-mail.domain}
    skip_verify: true
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        url: http://influxdb.metrics:8086
        access: proxy
        jsonData:
          version: Flux
          organization: ${influx.organization}
          defaultBucket: ${influx.bucket}
          tlsSkipVerify: true
        secureJsonData:
          token: ${influx.token}
